import {describe,expect,it,vi} from 'vitest';
import {Config,normalizeConfig} from '@/src/core/config/model';
import {driveSyncPayload,toDriveSyncConfig} from '@/src/core/config/driveSync';
import {decryptDriveConfig,encryptDriveConfig} from '@/src/platform/google-drive/encryption';
import {createWebDavConnectionStore,parseWebDavConnection,WEBDAV_CONNECTION_KEY} from '@/src/platform/webdav/connection';
import {createWebDavBackup,type WebDavBackupPorts} from '@/src/services/config/webDavBackup';
import type {CloudSyncRemote} from '@/src/core/config/cloudSync';
import type {DriveSyncState} from '@/src/services/config/remoteConfigSync';
const password='FluentReadEncryption';
const input={url:'https://dav.fixture.invalid/base/',username:'fixture-user',password:'fixture-app-password',revision:null};
const config=(patch:Record<string,unknown>={})=>toDriveSyncConfig(normalizeConfig({...new Config(),videoServiceDefaultMigrated:true,...patch}));
function fixture(shared={remote:null as CloudSyncRemote|null}) {
    const records=new Map<string,unknown>();
    let local=config({token:{openai:'fixture-api-key'},customHeaders:{openai:'{"Authorization":"fixture-header"}'},customBody:{openai:'{"auth":"fixture-body"}'},proxy:{openai:'https://fixture.invalid/?auth=fixture-url-token'},extra:{oauth:'fixture-oauth-token'}});
    let state:unknown=null;
    const connections=createWebDavConnectionStore({getItem:async<T>(key:string)=>(records.get(key)??null) as T|null,setItem:async(key,value)=>{records.set(key,value);},removeItem:async key=>{records.delete(key);}});
    const ports:WebDavBackupPorts={connections,api:{test:vi.fn(async()=>undefined),read:vi.fn(async()=>shared.remote),write:vi.fn(async(_session,content)=>{shared.remote={file:{id:'fixture-file',version:crypto.randomUUID(),modifiedTime:''},content};return shared.remote.file;})},snapshot:vi.fn(async()=>structuredClone(local)),apply:vi.fn(async value=>{local=structuredClone(value);}),readState:vi.fn(async()=>state),writeState:vi.fn(async value=>{state=value;}),removeState:vi.fn(async()=>{state=null;}),now:()=>1000};
    const service=createWebDavBackup(ports);
    return {service,ports,records,connections,shared,get state(){return state as DriveSyncState;},get local(){return local;},set local(value){local=value;}};
}
describe('WebDAV 配置云备份事务',()=>{
    it('打开页面只读本机摘要；测试和保存连接均不创建云端文件',async()=>{
        const f=fixture();
        expect(await f.service.status()).toMatchObject({available:false,account:null});
        expect(await f.service.settings()).toBeNull();
        await expect(f.service.prepare(password)).rejects.toMatchObject({code:'missing'});
        expect(f.ports.api.read).not.toHaveBeenCalled();
        await f.service.test(input);expect(await f.service.settings()).toBeNull();
        const saved=await f.service.save(input,7,'fixture-page');
        expect(saved).toMatchObject({url:input.url,username:input.username,hasPassword:true});
        expect(JSON.stringify(saved)).not.toContain(input.password);
        expect(await f.service.status()).toMatchObject({available:true,account:null});
        expect(f.ports.api.write).not.toHaveBeenCalled();
        expect(f.shared.remote).toBeNull();
        await expect(f.service.save(input)).rejects.toMatchObject({code:'changed'});
        vi.mocked(f.ports.api.test).mockRejectedValueOnce(new Error('fixture test failure'));
        await expect(f.service.save({...saved,password:'changed-fixture'})).rejects.toThrow('fixture test');
        expect(await f.service.settings()).toEqual(saved);
    });
    it('后台重启后恢复一次性预览，完整凭据可在第二设备恢复；连接密码不进入备份',async()=>{
        const f=fixture();
        const appearance={backgroundColor:'#fce7f3',customCss:'color: #123456;'};
        f.local=config({...f.local,bilingualSentenceHighlightAppearance:appearance,bilingualSentenceHighlightProfiles:[{id:'fixture-highlight',name:'Fixture highlight',style:'mint',appearance}],activeSentenceHighlightProfileId:'fixture-highlight'});
        await f.service.save(input);
        const preview=await f.service.prepare(password,7,'fixture-page');
        expect(preview).toMatchObject({hasRemote:false,hasBaseline:false,changes:[]});
        expect(f.ports.api.write).not.toHaveBeenCalled();
        expect(JSON.stringify(f.state)).not.toMatch(/fixture-api-key|fixture-app-password|fixture-oauth-token/u);
        await createWebDavBackup(f.ports).commit(preview.id,password,'upload',{},7,'fixture-page');
        const cloud=f.shared.remote!;
        for(const value of ['fixture-api-key','fixture-header','fixture-body','fixture-url-token','fixture-oauth-token',input.password]) expect(cloud.content).not.toContain(value);
        const payload=await decryptDriveConfig(cloud.content,password) as {config:unknown};
        expect(payload.config).toEqual(f.local);
        expect(JSON.stringify(payload)).not.toContain(input.password);
        const last=await f.service.status();expect(last.account?.email).toContain('fixture-user');
        const second=fixture(f.shared);await second.service.save(input);second.local=config({token:{openai:'fixture-old-key'},key:'fixture-delete-key'});
        const restore=await second.service.prepare(password,8,'fixture-other');
        expect(restore.hasBaseline).toBe(false);
        await second.service.commit(restore.id,password,'download',{},8,'fixture-other');
        expect(second.local).toEqual(f.local);
        expect(second.local).toMatchObject({bilingualSentenceHighlightAppearance:appearance,bilingualSentenceHighlightProfiles:[{id:'fixture-highlight',style:'mint',appearance}],activeSentenceHighlightProfileId:'fixture-highlight'});
        expect(second.ports.api.write).not.toHaveBeenCalled();
        expect(second.shared.remote).toEqual(cloud);
        await expect(second.service.commit(restore.id,password,'download',{},8,'fixture-other')).rejects.toThrow('失效');
    });
    it('相同连接保留基线，换连接使预览失效；另一页面不能更改连接或取消事务',async()=>{
        const f=fixture();
        let saved=await f.service.save(input,7,'fixture-page');
        let preview=await f.service.prepare(password,7,'fixture-page');
        for(const action of ['save','clear'] as const) await expect(action==='save'?f.service.save({...saved,password:''},8,'fixture-other'):f.service.clear(saved.revision,8,'fixture-other')).rejects.toThrow('另一个设置页面');
        await expect(f.service.save({...saved,password:''},7,'fixture-other')).rejects.toThrow('另一个设置页面');
        await f.service.cancel(preview.id,8,'fixture-other');expect(f.state.prepared?.id).toBe(preview.id);
        await f.service.cancelTab(99);expect(f.state.prepared?.id).toBe(preview.id);
        await f.service.cancelTab(7);expect(f.state.prepared).toBeUndefined();
        preview=await f.service.prepare(password,7,'fixture-page');await f.service.commit(preview.id,password,'upload',{},7,'fixture-page');
        const same=await f.service.save({...saved,password:''},7,'fixture-page');expect(same.revision).toBe(saved.revision);
        preview=await f.service.prepare(password,7,'fixture-page');expect(preview.hasBaseline).toBe(true);await f.service.cancel(preview.id,7,'fixture-page');
        preview=await f.service.prepare(password,7,'fixture-page');
        const changed=parseWebDavConnection({...saved,password:'fixture-other-password'},await f.connections.read());
        // 模拟后台外部连接修改，旧确认不能写入任一服务器。
        await f.connections.write(changed);
        const writes=vi.mocked(f.ports.api.write).mock.calls.length;
        await expect(f.service.commit(preview.id,password,'upload',{},7,'fixture-page')).rejects.toThrow('同步连接已变化');
        expect(vi.mocked(f.ports.api.write).mock.calls.length).toBe(writes);
        const firstForNewConnection=await f.service.prepare(password,7,'fixture-page');expect(firstForNewConnection.hasBaseline).toBe(false);
        await f.service.cancel(firstForNewConnection.id,7,'fixture-page');
        saved=(await f.service.settings())!;
        const changedSummary=await f.service.save({...saved,password:'fixture-new-password'},7,'fixture-page');
        expect(changedSummary.revision).not.toBe(saved.revision);
        saved=changedSummary;
        // 已过期预览不锁住连接设置。
        vi.mocked(f.ports.readState).mockResolvedValueOnce({...f.state,prepared:{id:'expired',expiresAt:0,tabId:9,clientId:'expired'}} as unknown as DriveSyncState);
        await f.service.save({...saved,password:''},7,'fixture-page');
        await expect(f.service.clear('stale',7,'fixture-page')).rejects.toMatchObject({code:'changed'});
        const cloud=f.shared.remote;
        await f.service.clear(saved.revision,7,'fixture-page');
        expect(await f.service.settings()).toBeNull();expect(f.state).toBeNull();expect(f.shared.remote).toEqual(cloud);
        await f.service.clear(null,7,'fixture-page');expect(f.records.has(WEBDAV_CONNECTION_KEY)).toBe(false);
    });
    it('合并单边修改，云端和本机变化使预览失效；失败不更新成功记录',async()=>{
        const f=fixture();await f.service.save(input);
        let preview=await f.service.prepare(password);await f.service.commit(preview.id,password,'upload',{});
        const baseline=f.state;const original=f.local;
        f.local=config({...original,theme:'dark'});
        f.shared.remote={file:{...f.shared.remote!.file,version:'2'},content:await encryptDriveConfig(driveSyncPayload(config({...original,to:'fr'})),password)};
        preview=await f.service.prepare(password);await f.service.commit(preview.id,password,'merge',{});
        expect(f.local).toMatchObject({theme:'dark',to:'fr'});
        preview=await f.service.prepare(password);f.local=config({...f.local,to:'de'});
        await expect(f.service.commit(preview.id,password,'upload',{})).rejects.toThrow('本机配置已变化');
        preview=await f.service.prepare(password);f.shared.remote={...f.shared.remote!,file:{...f.shared.remote!.file,version:'changed'}};
        await expect(f.service.commit(preview.id,password,'upload',{})).rejects.toThrow('云端配置已变化');
        const previous=f.state;preview=await f.service.prepare(password);vi.mocked(f.ports.api.write).mockRejectedValueOnce(new Error('fixture upstream'));
        await expect(f.service.commit(preview.id,password,'upload',{})).rejects.toThrow('fixture upstream');expect(f.state).toEqual(previous);
        expect(baseline.lastSyncedAt).toBe(1000);
    });
});
